server:
 port: 8090
# setting Database spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Spring Boot Actuator expondrá solo un conjunto limitado de endpoints de
#forma predeterminada [/actuator/health, /actuator/info]
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reto
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

